// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtYgtXUXhJ68989KlZIvAcq2c1bQpBREc',
    appId: '1:190003618365:android:c79f14082b2ec2bd8bc054',
    messagingSenderId: '190003618365',
    projectId: 'machina-be9a0',
    storageBucket: 'machina-be9a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxqWYCYbPxzHxJZP7HQfL1o0-p2gJthPI',
    appId: '1:190003618365:ios:0550cddb52611e9b8bc054',
    messagingSenderId: '190003618365',
    projectId: 'machina-be9a0',
    storageBucket: 'machina-be9a0.appspot.com',
    iosClientId: '190003618365-4ec39ofulosl1nianf24q6rn0kkp2b3l.apps.googleusercontent.com',
    iosBundleId: 'com.autoapp.application.flutterProjects',
  );
}
